// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/models/config/config.go

// Package config is a generated GoMock package.
package config

import (
	reflect "reflect"

	dnsalias "github.com/equinor/radix-operator/pkg/apis/config/dnsalias"
	v1 "github.com/equinor/radix-operator/pkg/apis/radix/v1"
	gomock "github.com/golang/mock/gomock"
	logrus "github.com/sirupsen/logrus"
)

// MockConfig is a mock of Config interface.
type MockConfig struct {
	ctrl     *gomock.Controller
	recorder *MockConfigMockRecorder
}

// MockConfigMockRecorder is the mock recorder for MockConfig.
type MockConfigMockRecorder struct {
	mock *MockConfig
}

// NewMockConfig creates a new mock instance.
func NewMockConfig(ctrl *gomock.Controller) *MockConfig {
	mock := &MockConfig{ctrl: ctrl}
	mock.recorder = &MockConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfig) EXPECT() *MockConfigMockRecorder {
	return m.recorder
}

// GetAppName mocks base method.
func (m *MockConfig) GetAppName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAppName indicates an expected call of GetAppName.
func (mr *MockConfigMockRecorder) GetAppName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppName", reflect.TypeOf((*MockConfig)(nil).GetAppName))
}

// GetAppNamespace mocks base method.
func (m *MockConfig) GetAppNamespace() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppNamespace")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAppNamespace indicates an expected call of GetAppNamespace.
func (mr *MockConfigMockRecorder) GetAppNamespace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppNamespace", reflect.TypeOf((*MockConfig)(nil).GetAppNamespace))
}

// GetBranch mocks base method.
func (m *MockConfig) GetBranch() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBranch")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetBranch indicates an expected call of GetBranch.
func (mr *MockConfigMockRecorder) GetBranch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBranch", reflect.TypeOf((*MockConfig)(nil).GetBranch))
}

// GetDNSConfig mocks base method.
func (m *MockConfig) GetDNSConfig() *dnsalias.DNSConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDNSConfig")
	ret0, _ := ret[0].(*dnsalias.DNSConfig)
	return ret0
}

// GetDNSConfig indicates an expected call of GetDNSConfig.
func (mr *MockConfigMockRecorder) GetDNSConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDNSConfig", reflect.TypeOf((*MockConfig)(nil).GetDNSConfig))
}

// GetGitConfigMapName mocks base method.
func (m *MockConfig) GetGitConfigMapName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGitConfigMapName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetGitConfigMapName indicates an expected call of GetGitConfigMapName.
func (mr *MockConfigMockRecorder) GetGitConfigMapName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGitConfigMapName", reflect.TypeOf((*MockConfig)(nil).GetGitConfigMapName))
}

// GetGitRepositoryWorkspace mocks base method.
func (m *MockConfig) GetGitRepositoryWorkspace() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGitRepositoryWorkspace")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetGitRepositoryWorkspace indicates an expected call of GetGitRepositoryWorkspace.
func (mr *MockConfigMockRecorder) GetGitRepositoryWorkspace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGitRepositoryWorkspace", reflect.TypeOf((*MockConfig)(nil).GetGitRepositoryWorkspace))
}

// GetLogLevel mocks base method.
func (m *MockConfig) GetLogLevel() logrus.Level {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogLevel")
	ret0, _ := ret[0].(logrus.Level)
	return ret0
}

// GetLogLevel indicates an expected call of GetLogLevel.
func (mr *MockConfigMockRecorder) GetLogLevel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogLevel", reflect.TypeOf((*MockConfig)(nil).GetLogLevel))
}

// GetPipelinesAction mocks base method.
func (m *MockConfig) GetPipelinesAction() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPipelinesAction")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPipelinesAction indicates an expected call of GetPipelinesAction.
func (mr *MockConfigMockRecorder) GetPipelinesAction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPipelinesAction", reflect.TypeOf((*MockConfig)(nil).GetPipelinesAction))
}

// GetRadixConfigBranch mocks base method.
func (m *MockConfig) GetRadixConfigBranch() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRadixConfigBranch")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetRadixConfigBranch indicates an expected call of GetRadixConfigBranch.
func (mr *MockConfigMockRecorder) GetRadixConfigBranch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRadixConfigBranch", reflect.TypeOf((*MockConfig)(nil).GetRadixConfigBranch))
}

// GetRadixConfigFileName mocks base method.
func (m *MockConfig) GetRadixConfigFileName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRadixConfigFileName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetRadixConfigFileName indicates an expected call of GetRadixConfigFileName.
func (mr *MockConfigMockRecorder) GetRadixConfigFileName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRadixConfigFileName", reflect.TypeOf((*MockConfig)(nil).GetRadixConfigFileName))
}

// GetRadixConfigMapName mocks base method.
func (m *MockConfig) GetRadixConfigMapName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRadixConfigMapName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetRadixConfigMapName indicates an expected call of GetRadixConfigMapName.
func (mr *MockConfigMockRecorder) GetRadixConfigMapName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRadixConfigMapName", reflect.TypeOf((*MockConfig)(nil).GetRadixConfigMapName))
}

// GetRadixDeployToEnvironment mocks base method.
func (m *MockConfig) GetRadixDeployToEnvironment() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRadixDeployToEnvironment")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetRadixDeployToEnvironment indicates an expected call of GetRadixDeployToEnvironment.
func (mr *MockConfigMockRecorder) GetRadixDeployToEnvironment() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRadixDeployToEnvironment", reflect.TypeOf((*MockConfig)(nil).GetRadixDeployToEnvironment))
}

// GetRadixImageTag mocks base method.
func (m *MockConfig) GetRadixImageTag() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRadixImageTag")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetRadixImageTag indicates an expected call of GetRadixImageTag.
func (mr *MockConfigMockRecorder) GetRadixImageTag() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRadixImageTag", reflect.TypeOf((*MockConfig)(nil).GetRadixImageTag))
}

// GetRadixPipelineJobName mocks base method.
func (m *MockConfig) GetRadixPipelineJobName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRadixPipelineJobName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetRadixPipelineJobName indicates an expected call of GetRadixPipelineJobName.
func (mr *MockConfigMockRecorder) GetRadixPipelineJobName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRadixPipelineJobName", reflect.TypeOf((*MockConfig)(nil).GetRadixPipelineJobName))
}

// GetRadixPipelineType mocks base method.
func (m *MockConfig) GetRadixPipelineType() v1.RadixPipelineType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRadixPipelineType")
	ret0, _ := ret[0].(v1.RadixPipelineType)
	return ret0
}

// GetRadixPipelineType indicates an expected call of GetRadixPipelineType.
func (mr *MockConfigMockRecorder) GetRadixPipelineType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRadixPipelineType", reflect.TypeOf((*MockConfig)(nil).GetRadixPipelineType))
}

// GetRadixPromoteDeployment mocks base method.
func (m *MockConfig) GetRadixPromoteDeployment() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRadixPromoteDeployment")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetRadixPromoteDeployment indicates an expected call of GetRadixPromoteDeployment.
func (mr *MockConfigMockRecorder) GetRadixPromoteDeployment() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRadixPromoteDeployment", reflect.TypeOf((*MockConfig)(nil).GetRadixPromoteDeployment))
}

// GetRadixPromoteFromEnvironment mocks base method.
func (m *MockConfig) GetRadixPromoteFromEnvironment() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRadixPromoteFromEnvironment")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetRadixPromoteFromEnvironment indicates an expected call of GetRadixPromoteFromEnvironment.
func (mr *MockConfigMockRecorder) GetRadixPromoteFromEnvironment() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRadixPromoteFromEnvironment", reflect.TypeOf((*MockConfig)(nil).GetRadixPromoteFromEnvironment))
}

// GetSourceDeploymentGitBranch mocks base method.
func (m *MockConfig) GetSourceDeploymentGitBranch() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSourceDeploymentGitBranch")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSourceDeploymentGitBranch indicates an expected call of GetSourceDeploymentGitBranch.
func (mr *MockConfigMockRecorder) GetSourceDeploymentGitBranch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSourceDeploymentGitBranch", reflect.TypeOf((*MockConfig)(nil).GetSourceDeploymentGitBranch))
}

// GetSourceDeploymentGitCommitHash mocks base method.
func (m *MockConfig) GetSourceDeploymentGitCommitHash() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSourceDeploymentGitCommitHash")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSourceDeploymentGitCommitHash indicates an expected call of GetSourceDeploymentGitCommitHash.
func (mr *MockConfigMockRecorder) GetSourceDeploymentGitCommitHash() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSourceDeploymentGitCommitHash", reflect.TypeOf((*MockConfig)(nil).GetSourceDeploymentGitCommitHash))
}

// GetWebhookCommitId mocks base method.
func (m *MockConfig) GetWebhookCommitId() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebhookCommitId")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetWebhookCommitId indicates an expected call of GetWebhookCommitId.
func (mr *MockConfigMockRecorder) GetWebhookCommitId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebhookCommitId", reflect.TypeOf((*MockConfig)(nil).GetWebhookCommitId))
}
